### ISSUE TITLE
User signup allowing spaces in username.

### ISSUE THREAD

**Issue by branjames117** [branjames117/devspark#12]
Another bit of client-side (and server-side) validation we need to implement is, users should not be allowed to have spaces in their usernames, or email addresses for that matter. Here's a simple regex test that can detect if an input (string) has any white space.

```
if (/\s/.test(str)) {
    // string has white space, invalid input! tell the user about it!
}
```

**Comment by Cody-Junier** [comment]
Placed code in branch, awaiting PR.
