### ISSUE TITLE
Create an actual profile route, with GitHub Issues.

### ISSUE THREAD

**Issue by branjames117** [branjames117/devspark#13]
In html-routes, we need a router.get('/profile/:id') where id is the ID of the user. Server will then use that id (req.params.id), query the database, and if it finds a user, sends that data to the view engine as an object to be rendered to the page. No need to style anything, just get all the data on the screen, including your **github issues**.

**Comment by branjames117** [comment]
Also add to the profile a link "Message this user", and it links to /chat/:id, where :id is the user's ID.

**Comment by branjames117** [comment]
Routes are live, but we need to plug in the GitHub Issues to the profile page now.

**Comment by Cody-Junier** [comment]
I have GitHub Issues functionality in home.handlebars and home.js, simply need to add home.handlebars to partials, then link it inside of profile.handlebars

**Comment by Cody-Junier** [comment]
Pushing fix up now...
